# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish release to NPM.js

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "yarn"
          cache-dependency-path: yarn.lock
          always-auth: true
      - run: yarn install
      - run: yarn ci
      - run: yarn test
      - run: yarn publish --access public packages/shared
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
      - run: yarn publish --access public packages/host
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
      - run: yarn publish --access public packages/client
        env:
          NPM_AUTH_TOKEN: ${{secrets.NPMJS_TOKEN}}
